### PR TITLE
Incorporate liball load balancing library

### PR DESCRIPTION
**Pull request by aetx**
The corresponding changes in https://github.com/ECP-copa/Cabana/pull/439 (or the `all_lb` branch) are needed for this to work.

This will incorporate the load balancer https://gitlab.jsc.fz-juelich.de/SLMS/loadbalancing into the ExaMPM setup.

Note: The dam break partitioning is in z-direction to create a larger load imbalance.

Current state seems to be a bit broken when reading the local grid location and extent, but the number of particles seems to be balanced.

### CODE REVIEW

**Comment by junghans** [comment]
@aetx I had it so it pulls your `all_lb` branch from Cabana, but it still fails to build.

**Comment by junghans** [comment]
Great it works now, so we should merge https://github.com/ECP-copa/Cabana/pull/439 first and then revert ee32eebef2842443697462db208b35ce44afe508.

**Comment by junghans** [comment]
Ist there a chance to make liball an optional dependency?

**Comment by aetx** [comment]
This should make ALL optional in the same way that, e.g., ArborX is optional in Cabana. I.e. if found automatically it is enabled and it can be required as well. Although it might also be useful to forcefully disable it I suppose.

**Comment by aetx** [comment]
Still need to propagate the preprocessor define.

**Comment by aetx** [comment]
The load balancer will be integrated into Cabana/Cajita itself, so this explicit usage is no longer needed.

**Pull request closed without merging**
